---
title: "Analyze REFLIN times"
author: "John Minter"
date: 'Started 2018-08-12, Last modified: 2018-08-12'
output:
  html_document:
    css: ../../../inc/jm.css
    number_sections: yes
    toc: yes
  pdf_document:
    toc: yes
abstract: |
  The objective was to understand the change in simulation times as a
  function of the tolerance setting. I used a series of simulations
  using the `Zn L3-M4` transition to reach the `REFLIN` criterion
  using values of $[5.0e^{-1}, 4.0e^{-1}, 3.0e^{-1}, 2.0e^{-1}, 1.0e^{-1}]$.
  This was a fairly weak transition (0.1140) compared to the
  stronger `Zn L3-M5` transition (1.0). Still, I want to see how the
  simulation scales with the value of the uncertainty criterion.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE,
  comment = NA,
  fig.align = "centre",
  fig.height = 4,
  message = FALSE,
  warning = FALSE,
  error = FALSE)
```

# Set up for the analysis

## Load the libraries we need

```{r loadPackages}
library(rpenepma)
library(readr)
library(dplyr)
library(pander)
panderOptions('table.split.table', Inf)
library(ggplot2)
```

## Read in the data

```{r readData}
tib <- read_csv("reflin-test-stats.csv")
pander(tib)
```

# Plot the data

## Plot $tol = f(hrs)$
```{r plot_tol_vs_time}
tol_vs_time_plt <- ggplot(tib, aes(x = tol, y = hrs)) +
               geom_point() 

print(tol_vs_time_plt)
```

## Plot $\frac{1}{tol} = f(hrs)$

```{r plot_inv_tol_vs_time}
inv_tol_vs_time_plt <- ggplot(tib, aes(x = 1/tol, y = hrs)) +
                       geom_point() +
                       stat_smooth(method = 'lm',
                                   formula = y ~ I(x^2) + 0,
                                   aes(' ' = 'darkblue'),
                                   se = FALSE) 

print(inv_tol_vs_time_plt)
```

## Fit a second order polynomial to the system

Model the system as a second order polynomial with a zero intercept.

```{r polyModel}
x <- 1.0 / tib$tol
y <- tib$hrs

poly_mod <- lm(y ~ I(x^2) + 0)
pander(summary(poly_mod))

```


```{r plot_tol_vs_showers}
tol_vs_time_showers_plt <- ggplot(tib, aes(x = tol, y = showers)) +
                           geom_point() 

print(tol_vs_time_showers_plt)
```

## Add a data transformation

```{r minus_log_trans}

mod_tib <- tib %>%
              mutate(m_log_show = -log(showers)) %>%
              mutate(m_log_hrs = log(hrs))
mod_tib
```

```{r plot_tol_vs_log_time}
tol_vs_m_log_hrs_plt <- ggplot(mod_tib, aes(x = tol, y = m_log_hrs)) +
                        geom_point() +
                        stat_smooth(method='loess', span = 1.5)

print(tol_vs_m_log_hrs_plt)
```
