# Plots the spectrum generated by 'penepma.f'
set zero 1.0e-60
set xzeroaxis
set xrange [0:8]
set yrange [1e-11:*]
set title 'PENEPMA Simulation of K530 and K412 at 15 kV'
set xlabel "energy [keV]"
set ylabel "PDF [1/(eV*sr*electron)]"
set logscale y
plot 'K530-pe-spect-01.dat' u ($1/1000.):2:3 w lines lw 1 lc rgb "#0000A0" title "K530", 'K412-pe-spect-01.dat' u ($1/1000.):2:3 w lines lw 1 lc rgb "#800000" title "K412"